#!/bin/bash

#Sets environment variables for use by all other scripts in this group
#
# "$ source herons_set_vars"
#

#If an IP address changes, only change it here
export ABEF="192.168.1.173"
export ABEB="192.168.14.100"
export BENF="192.168.1.174"
export BENB="192.168.15.100"
export CALF="192.168.1.169"
export CALB="192.168.16.100"
export DEBF="192.168.1.168"
export DEBB="192.168.17.100"
export EVEF="192.168.1.167"
export EVEB="192.168.18.100"
export FINF="192.168.1.149"
export FINB="192.168.19.100"
export MAXF="192.168.1.148"
export MAXB="192.168.20.100"
export NEDF="192.168.1.147"
export NEDB="192.168.21.100"
export OAKF="192.168.1.146"
export OAKB="192.168.22.100"
export PIPF="192.168.1.145"
export PIPB="192.168.23.100"


#todo: maybe export name indices as well, i.e. abe_f_x = 0

export HERONS_CPUS="$ABEF,$ABEB,$BENF,$BENB,$CALF,$CALB,$DEBF,$DEBB,$EVEF,$EVEB,$FINF,$FINB,$MAXF,$MAXB,$NEDF,$NEDB,$OAKF,$OAKB,$PIPF,$PIPB"
export HERONS_CPUS_N="ABEF,ABEB,BENF,BENB,CALF,CALB,DEBF,DEBB,EVEF,EVEB,FINF,FINB,MAXF,MAXB,NEDF,NEDB,OAKF,OAKB,PIPF,PIPB"
